remote_theme: pages-themes/slate@v0.2.0
plugins: 
  - jekyll-remote-theme 
title: GRAVI
decription: "Developed By Stephen Pederson <br> Dame Roma Mitchell Cancer Research Laboratories, University of Adelaide"