remote_theme: pages-themes/slate@v0.2.0
plugins: 
  - jekyll-remote-theme 
title: "GRAVI: Gene Regulatory Analysis using Variable Inputs"
decription: >
  Developed By Stephen Pederson
  Dame Roma Mitchell Cancer Research Laboratories, University of Adelaide