## Plot colours propagated through all markdown documents for
## consistency. Treat colours must match all treatments specified in config.yml
## with the addition of a colour for input/control samples
qc:
  pass: "#0571B0"
  fail: "#CA0020"
regions:
  promoters: '#FF3300'
  upstream: '#E1EE05'
  exons: '#7EDD57'
  introns: '#006600'
  proximal: '#000066'
  distal: '#551A8B'
treat:
  Input: "#33333380"
  Control: "#4D4D4D"
  Treat: "#C53270"
features:
  promoter: "#FF4500"
  enhancer: "#FFFF00"
  super_enhancer: "#FFC34D"
  no_feature: "#E5E5E5"
direction:
  up: "#CA0020"
  down: "#0571B0"
  unchanged: "#7F7F7F"
  undetected: "#E5E5E5"
heatmaps: ['white', 'red']
