## Please see https://smped.github.io/GRAVI/editing-yaml.html for a description of this file
samples:
  file: "config/samples.tsv"

paths:
  bam: "data/bam"

genome:
  build: "GRCh37"

## Both macs2 fields are now updated so there is a default
## This is passed to all targets, however, if a different value is required
## in any field for a specific target, then adding that field for the given
## target can be done, e.g. AR: fdr: 0.01 (in the correct YAML format)
macs2:
  default:
    gsize: "hs"
    fdr: 0.05
    keep_duplicates: "all"   

macs2_qc:
  default:
    outlier_threshold: 10
    allow_zero: true
    min_prop_reps: 0.5 # Currently, this cannot be set within a given target

## Set the defaults across all targets here and set any changes as desired
## for any specific target
differential_signal:
  default:
    window_type: "fixed"
    window_size: 400 
    window_step: 
    filter_q: 
    method: "qlf"
    norm: "TMM"
    fc: 1.2
    fdr: 0.05
    pair_column: 
    contrasts:
      - ["E2", "E2DHT"]
    ihw: "targets"
  H3K27ac:
    window_type: "sliding"
    window_size: 180
    window_step: 60
    filter_q: 0.7


comparisons:
  windows:
    size: 120
    step: 40
  filter_q: 0.6
  method: "sq-lt"
  fc: 1.2
  fdr: 0.05
  paired: false
  contrasts:
    - ["E2", "E2DHT"]
  ihw: "targets"

external:
  blacklist: 
  gtf: 
  rnaseq:
  features:
  hic:
  coverage:


