## Add relevant sample information here.
## The fields are essentially fixed, although multiple treatments can be
## included
samples:
  file: "config/samples.tsv"

paths:
  bam: "data/aligned"
  bigwig: "data/bigwig"
  macs2: "data/macs2"

## These will be applied to **all** targets containing both levels specified in
## the contrasts field. The first provided level will be considered as the
## baseline/control/reference.
## Fields provided in the ihw field can only be blank ("") or one of:
## "targets": Will use all other ChIP targets in the samples file
## "regions": Will use Genomic Regions as defined during the annotation setup
## "features": Will use any ranges provided as external features (below)
## This will be used for obtaining an IHW-adjusted FDR.
comparisons:
  fc: 1.2
  fdr: 0.05
  paired: false
  filter_q: 0.6
  contrasts:
    - ["Veh", "DHT"]
  ihw: "regions"


## Currently, this workflow assumes alignments are provided as bam files
## Metadata is set to be obtained from gencode. This may need changing later.
## Please use GRCh37/38 for the build argument. hg19/38 will be detected from
## these
genome:
  build: "GRCh37"
  gencode: "33"

## Additional data to be incorporated. Fields are fixed.
## Features shoould be provided as a gtf
## HiC data should be a single rds file prepared independently of this workflow
## Change this to a bedpe
external:
  rnaseq: "data/external/PDX_HCI-005_Veh_DHT_Sarm_RNASeq.tsv"
  features: "data/external/h3k27ac_features.gtf"
  hic:
  coverage:
    H3K27Ac:
      Veh: "data/external/H3K27Ac_Veh.bw"
      DHT: "data/external/H3K27Ac_DHT.bw"

peaks:
  ## Settings for macs2 callpeak
  macs2:
    gsize: "hs"
    fdr: 0.05
    keep_duplicates: "all"
  qc:
    ## Any sample retaining fewer than *min_prop_peaks* relative to the sample
    ## with the maximal number of retained peaks, will be considered as failing
    ## QC. This will ensure samples will be retained in the absence of signal,
    ## but discarded with an experimental failure
    ## When determining oracle peaks, require peaks to be detected in more than
    ## *min_prop_reps* of the replicates, after excluding failed replicates
    ## using min_prop_peaks. Higher values are more applicable for cell lines
    ## (e.g. >0.5) whilst PDX/organoid lines may need lower values (e.g. 0.3)
    ## given the difficulty of working with solid tissue
    min_prop_peaks: 0.1
    min_prop_reps: 0.3

