## Please see https://smped.github.io/GRAVI/editing-yaml.html for a description of this file
samples:
  file: "config/samples.tsv"

paths:
  bam: "data/bam"

genome:
  build: "GRCh37"

## Both macs2 fields are now updated so there is a default
## This is passed to all targets, however, if a different value is required
## in any field for a specific target, then adding that field for the given
## target can be done, e.g. AR: fdr: 0.01 (in the correct YAML format)
macs2:
  default:
    gsize: "hs"
    fdr: 0.05
    keep_dup: "all"
    extra: ""

peak_qc:
  default:
    outlier_threshold: 10
    allow_zero: false
    min_prop_reps: 0.5

motif_analysis:
  default:
    abs: true
    adj: "fdr"
    alpha: 0.05
    binwidth: 10
    ignore_below: 0.01
    iterations: 100
    model: "quasipoisson"
    peak_width: 400
    nfr: false

## Set the defaults across all targets here and set any changes as desired
## for any specific target
differential_signal:
  default:
    alpha: 0.05
    contrasts:
      - ["E2", "E2DHT"]
    ihw: "targets"
    fc: 1.2
    filter_q:
    method: "qlf"
    norm: "TMM"
    pair_column:
    window_type: "fixed"
    window_size: 400
    window_step:

external:
  blacklist:
  features:
  gtf:
  hic:
  motifdb:
  rna:


