## Please see https://steveped.github.io/GRAVI/editing-yaml.html for a description of this file
samples:
  file: "config/samples.tsv"

paths:
  bam: "data/bam"

genome:
  build: "GRCh37"
  gencode: "33"

peaks:
  macs2:
    gsize: "hs"
    fdr: 0.05
    keep_duplicates: "all"
  qc:
    outlier_threshold: 10
    allow_zero: true
    min_prop_reps: 0.5

comparisons:
  windows:
    size: 120
    step: 40
  filter_q: 0.6
  method: "sq-lt"
  fc: 1.2
  fdr: 0.05
  paired: false
  contrasts:
    - ["Control", "Treat"]
  ihw: "regions"

external:
  rnaseq:
  features:
  hic:
  coverage:


