## This file contains additional parameters which can be modified, but are
## generally not required to be modified

## The key values used when defining gene-centric regions
gene_regions:
  promoters:
    upstream: 1500
    downstream: 500
  upstream: 5000
  intergenic: 10000

## The categories to use from MSigDB. These are passed to msigdbr in the
## columns of the same name
msigdb:
  gs_cat: "H"
  gs_subcat:
    - "CP:KEGG"
    - "CP:REACTOME"
    - "CP:WIKIPATHWAYS"
    - "TFT:GTRD"
