## This file contains additional parameters which can be modified, but are
## generally not required to be modified

## The key values used when defining gene-centric regions
gene_regions:
  promoters:
    upstream: 1500
    downstream: 500
  upstream: 5000
  intergenic: 10000

## The values used when mapping peaks to genes.
## Passed to `extraChIPs::mapByFeature()`
## If including H3K27ac HiChIP for long range-interactions, it is advised to
## set `enh2gene` as zero, given that long range interactions in this case
## will more accurately map long-range enhancer interactions
mapping:
  gr2gene: 100000
  prom2gene: 0
  enh2gene: 100000
  gi2gene: 0

enrichment:
  adj: "fdr"
  alpha: 0.05
  ## Only gene-sets between these two values will be retained before testing
  min_size: 5
  max_size: 1000
  ## Only gene-sets above this size will be shown in the results
  min_sig: 3
  ## The categories to use from MSigDB. These are passed to msigdbr in the
  ## columns of the same name in an 'OR' approach
  msigdb:
    gs_cat: "H"
    gs_subcat:
      - "CP:KEGG"
      - "CP:REACTOME"
      - "CP:WIKIPATHWAYS"
      - "TFT:GTRD"

## Used for network plots
networks:
  min_size: 4
  max_size: 80
  max_distance: 0.9
  layout: 'fr'
